<?php

namespace App\Services;

use OpenAI\Laravel\Facades\OpenAI;
use Barryvdh\DomPDF\Facade\Pdf;
use Smalot\PdfParser\Parser;
use RuntimeException;

class AnalyzeResumeService
{
    /* =========================
     * PUBLIC API
     * ========================= */

    public function analyzeResume($resume): int
    {
        $cvText = $this->extractText($resume->getRealPath());
        return $this->analyzeWithAI($cvText);
    }

    public function improveResume($resume): array
    {
        $cvText = $this->extractText($resume->getRealPath());

        $name = $this->extractNameFromCv($cvText);
        $contactLine = $this->extractContactLine($cvText);

        $bodyHtml = $this->improveWithAI($cvText);

        return [
            'html' => $this->buildHeaderHtml(
                $name ?: 'Insert name here',
                $contactLine ?: 'Insert city, country • Insert email • Insert phone'
            ) . $bodyHtml,
            'name' => $name,
            'cvText' => $cvText,
        ];
    }

    public function downloadPdf(string $html, string $candidateName)
    {
        $pdf = $this->generatePdf($html);

        return response()->streamDownload(
            fn() => print($pdf),
            $this->buildFileName($candidateName)
        );
    }

    /* =========================
     * TEXT EXTRACTION
     * ========================= */

    private function extractText(string $path): string
    {
        if (!file_exists($path)) {
            throw new RuntimeException('Resume not found.');
        }

        if (str_ends_with(strtolower($path), '.pdf')) {
            return trim((new Parser())->parseFile($path)->getText());
        }

        return trim(file_get_contents($path));
    }

    /* =========================
     * AI — ANALYZE
     * ========================= */

    private function analyzeWithAI(string $cv): int
    {
        $prompt = "
            You are an ATS scoring engine embedded inside a CV optimization SaaS.

            IMPORTANT:
            This platform has a very strict internal CV formatting and writing standard.
            CVs produced by the platform's own improvement engine are considered
            near-optimal by definition.

            Your job is NOT to judge general CV perfection,
            but to measure how closely the CV matches THIS platform's standard.

            Return ONLY a number between 0 and 100.

            ====================
            SCORING ANCHOR (CRITICAL)
            ====================

            - If the CV already follows the platform's structure, formatting rules,
            and writing style, it MUST score between 80 and 100.
            - Only deduct points for clear deviations from the platform standard.
            - Do NOT penalize for missing metrics, seniority level,
            or subjective preferences.
            - Assume wording choices are intentional unless clearly weak.

            ====================
            FORMAT COMPLIANCE (PRIMARY WEIGHT)
            ====================

            Heavily reward the following:

            - Section titles clearly separated (preferably headings)
            - Work Experience entries structured EXACTLY as:
            1) Job Title – Company (no dates, no descriptions)
            2) Location — Date range
            3) Bullet points for achievements
            - Education entries using the same strict pattern
            - No tables, columns, icons, graphics, or decorative layout
            - Clean, ATS-safe structure

            A CV that follows this format should already score very high.

            ====================
            CONTENT QUALITY (SECONDARY WEIGHT)
            ====================

            Evaluate ONLY obvious issues:

            - Presence of action verbs in bullets
            - Achievement-oriented phrasing when possible
            - Clear, concise language
            - Logical section order

            Do NOT aggressively penalize stylistic differences.

            ====================
            ATS READABILITY (BASELINE)
            ====================

            - Plain text or simple HTML
            - Consistent formatting
            - Easy to parse by ATS systems

            ====================
            FINAL RULE
            ====================

            - CVs that look like they were generated by the platform's
            improvement engine should naturally score 80–100.
            - Reserve scores below 70 ONLY for CVs that clearly require restructuring.

            CV:
                {$cv}
            ";

        $response = OpenAI::chat()->create([
            'model' => 'gpt-4.1',
            'messages' => [
                ['role' => 'user', 'content' => $prompt],
            ],
        ])->choices[0]->message->content ?? '0';

        return (int) filter_var($response, FILTER_SANITIZE_NUMBER_INT);
    }

    /* =========================
     * AI — IMPROVE (HTML)
     * ========================= */
    private function improveWithAI(string $cvText): string
    {
        $prompt = "
            You are a professional CV rewriting engine.

            Rewrite and improve the CV to be ATS-friendly and professionally structured.
            Do NOT tailor it to any specific job offer.
            Do NOT invent information.

            ====================
            GLOBAL STRUCTURE RULES
            ====================

            - Section titles MUST ALWAYS be rendered as <h2> with bold text.
            - Section titles MUST NOT be bullet points.
            - Return ONLY clean HTML.
            - Do NOT include a profile or summary.
            - Do NOT include name or contact details.
            - Never invent information.
            - Use ONLY these HTML tags:
            h1, h2, p, ul, li, strong, em, u, span, br.

            ====================
            SCOPE OF STRICT FORMATTING (VERY IMPORTANT)
            ====================

            The STRICT formatting rules described below apply ONLY to:
            - Work Experience entries
            - Education entries

            They DO NOT apply to:
            - Skills
            - Technical Skills
            - Certifications
            - Academic Projects
            - Languages
            - Tools
            - Soft Skills
            - Any other section not explicitly listed above

            All other sections MUST be rendered in a normal, natural CV format
            using paragraphs and/or bullet points as appropriate.

            ====================
            WORK EXPERIENCE FORMAT (STRICT – NO EXCEPTIONS)
            ====================

            Each work experience entry MUST follow EXACTLY this structure:

            1) FIRST <p> — TITLE LINE
            - Wrapped in <strong>
            - Content ONLY:
            Job Title – Company / Experience Name
            - MUST NOT include:
            Dates, location, descriptions, responsibilities, skills, or extra context

            2) SECOND <p> — META LINE
            - Plain text (NO <strong>)
            - Content ONLY:
            Location — Date range
            - Date format MUST be:
            Month YYYY – Month YYYY
            OR
            Month YYYY – Present

            3) AFTER these two <p>:
            - Responsibilities / achievements MUST be bullet points (<ul><li>)
            - MAX 5 bullets per role

            ====================
            EDUCATION FORMAT (STRICT, WITH DESCRIPTION ALLOWED)
            ====================

            Each Education entry MUST follow EXACTLY this structure:

            1) FIRST <p>
            - Wrapped in <strong>
            - Content:
            Degree / Program – Institution

            2) SECOND <p>
            - Plain text (NO <strong>)
            - Content:
            Location — Date range OR expected graduation

            3) OPTIONAL THIRD <p> (ALLOWED AND ENCOURAGED):
            - Plain text
            - Used to describe:
            - Field of study
            - Campus
            - Relevant coursework
            - MUST be concise
            - MUST reflect information present in the original CV
            - MUST NOT include bullets

            ====================
            ALL OTHER SECTIONS (NORMAL FORMAT)
            ====================

            For sections such as Skills, Academic Projects, Certifications, Languages, etc.:

            - Use a natural CV format
            - Bullet points are allowed and encouraged where appropriate
            - No strict paragraph structure is required
            - Do NOT force the Experience/Education format here

            --- ORIGINAL CV ---
            {$cvText}
        ";

        return trim(
            OpenAI::chat()->create([
                'model' => 'gpt-4.1',
                'messages' => [
                    ['role' => 'user', 'content' => $prompt],
                ],
            ])->choices[0]->message->content ?? ''
        );
    }
    /* =========================
     * AI — EXTRACTION
     * ========================= */

    private function extractNameFromCv(string $cvText): string
    {
        return trim(OpenAI::chat()->create([
            'model' => 'gpt-4.1',
            'messages' => [[
                'role' => 'user',
                'content' => "Extract the candidate's full name. Return ONLY the name or \"Unknown\".\n\n{$cvText}"
            ]],
        ])->choices[0]->message->content);
    }

    private function extractContactLine(string $cvText): string
    {
        return trim(OpenAI::chat()->create([
            'model' => 'gpt-4.1',
            'messages' => [[
                'role' => 'user',
                'content' => "Extract location, email and phone in ONE line separated by •.\n\n{$cvText}"
            ]],
        ])->choices[0]->message->content);
    }

    /* =========================
     * PDF HELPERS
     * ========================= */

    private function buildHeaderHtml(string $name, string $contactLine): string
    {
        return <<<HTML
            <h1>{$name}</h1>
            <span>{$contactLine}</span>
        HTML;
    }

    private function buildFileName(?string $name): string
    {
        return preg_replace('/[\/\\\\]/', '-', ($name ?: 'Unknown') . '.pdf');
    }

    private function generatePdf(string $html): string
    {
        return Pdf::loadHTML("
            <html>
                <head>
                    <style>
                        body {
                            font-family: 'Calibri', sans-serif;
                            font-size: 12px; /* normal text */
                            font-weight: normal;
                            line-height: 1.4;
                            margin: 30px;
                        }

                        h1 {
                            font-family: 'Calibri', sans-serif;
                            font-size: 14px; /* Calibri bold 14 */
                            font-weight: bold;
                            margin-bottom: 4px;
                            text-align: center;
                            border-bottom: 1px solid #000;
                            padding-bottom: 4px;
                        }

                        h2, h3, h4, h5, h6 {
                            font-family: 'Calibri', sans-serif;
                            font-size: 12px; /* headings 11 */
                            font-weight: bold; /* bold for all subheadings */
                            margin-top: 15px;
                            margin-bottom: 4px;
                            border-bottom: 1px solid #000;
                            padding-bottom: 4px;
                        }

                        span {
                            font-family: 'Calibri', sans-serif;
                            font-size: 12px;
                            display: block;
                            text-align: center;
                        }

                        p {
                            margin-top: 0px;
                            padding-top: 0px;
                            margin-bottom: 0px;
                            padding-bottom: 0px;
                        }

                        ul {
                            margin-top: 0px;
                            padding-top: 0px;
                            margin-bottom: 0px;
                            padding-bottom: 0px;
                        }

                        li {
                            margin-top: 0px;
                            padding-top: 0px;
                            margin-bottom: 0px;
                            padding-bottom: 0px;
                        }
                    </style>
                </head>
                <body>
                    $html
                </body>
            </html>
        ")->output();
    }
}
